language: php

branches:
  only:
    - master
    - develop
        
php:
  - 5.2
  - 5.3
  - 5.4

services:
  - memcached
  - redis
  - mysql

notifications:
  email:
    on_success: change
    on_failure: never

before_script:
  - pear channel-discover pear.phpunit.de > /dev/null    # Selinium/PHPUnit Channel
  - pear install phpunit/PHPUnit_Selenium > /dev/null     # Add Selinium
  - mysql -e 'create database ciims_test;'          # Create Database
  - cd protected/runtime/                           # Download Yii Framework to Runtime Directory
  - git clone git://github.com/yiisoft/yii.git yii
  - cd ../
  - php yiic-test.php migrate up --interactive=0    # Run Migrations
  - cd tests                                        # Navigate to the Tests Directory to run the tests