language: php

branches:
  only:
    - master
    - develop    
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5

services:
  - memcached
  - redis
  - mysql

notifications:
  email:
    on_success: change
    on_failure: never

before_script:
  - mysql -e 'create database ciims_test;'          # Create Database
  - ls
  - cd protected/runtime/                           # Download Yii Framework to Runtime Directory
  - git clone git://github.com/yiisoft/yii.git yii
  - cd ../
  - php yiic.php migrate up --interactive=0         # Run Migrations
  - cd tests                                        # Navigate to the Tests Directory to run the tests
  
