language: php

php:
#  - 5.3 # Codeception 2.0 hardfails on PHP 5.3 due to dependency issues. No longer testing on
  - 5.4
  - 5.5
#  - hhvm

services:
  - memcached
  - redis
  - mysql

notifications:
  email:
    on_success: change
    on_failure: never
    
before_script:
  - composer selfupdate
  - composer update
  - php -i				
  - mysql -e 'create database ciims_test;'
  - php protected/tyiic.php migrate up --interactive=0

script: ./vendor/bin/codecept run
