language: php

env:
  global:
    secure: "Ug1yifDS73wE4wF7k+EyC42NKr8BGI0Z7p3O1swFt2+psDvUk+b8QCTOqRz1\nig0kdbYUGtvbBkc1H8SvSR8yEjV/pDPi2+b94hv2NwXzQ40C04f9jp16J67O\nT+iE/cczMInpwtLZoh8eax6BOIRglrQ3V6B211FLt513RbbHHqU="
    secure: "RcFoZDD5ezk3v7qhrzna+6q/WisX08zRkRHlpQbQJqQG09nFllMZfA6EyblL\n/igIrS2RaqJmaOrCLb2BmE1s8yIIrXsFfkivyL5PmuEUVNKM5hovTmODIBeT\nTiY5rzIsX6jt6ZGrOOPqXOdKNOhhcp5m3ffzSscOfjitnSriWuM="

branches:
  only:
    - master
    - develop
        
php:
  - 5.2
  - 5.3
  - 5.4

services:
  - memcached
  - redis
  - mysql

notifications:
  email:
    on_success: change
    on_failure: never

before_script:
  - pear channel-discover pear.phpunit.de | cat     # Selinium/PHPUnit Channel
  - pear install phpunit/PHPUnit_Selenium | cat     # Add Selinium
  - mysql -e 'create database ciims_test;'          # Create Database
  - cd protected/runtime/                           # Download Yii Framework to Runtime Directory
  - git clone git://github.com/yiisoft/yii.git yii
  - cd ../
  - php yiic-test.php migrate up --interactive=0    # Run Migrations
  - cd tests                                        # Navigate to the Tests Directory to run the tests

after_success:
  - echo "Host erianna" >> ~/.ssh/config            # Add necessary SSH credentials
  - echo "    Hostname erianna.com" >> ~/.ssh/config
  - echo "    User $USERNAME" >> ~/.ssh/config
  - echo "    StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "    UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  - gem install capistrano                          # Install Capistrano for Automated Deployment
  - cd ../                                          # Get the root Directory
  - git rev-parse --abbrev-ref HEAD > branch        # Derive the current branch name
  - ls -lah 
  - cat branch