language: php

php:
  - 5.3 # Codeception 2.0 hardfails on PHP 5.3 due to dependency issues. No longer testing on
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.3

services:
  - memcached
  - redis
  - mysql

notifications:
  email:
    on_success: change
    on_failure: never
    
before_script:
  - composer selfupdate
  - composer install # Install rather than update
  - php -i
  - mysql -e 'create database ciims_test;'
  - echo "2.0.0-dev" > protected/config/VERSION
  - php protected/yiic.php migrate up --interactive=0

script: ./vendor/bin/codecept run
