sudo: false # Use TravisCI new Docker container infrastructure

env:
  global:
    - secure: "U9q/v5DwZtVmRYjczFWIu49AP1RDBvWZasj+cqE+qUN+z8k7F+WvFlpoBfguKyT4utxlQCeu/2cUxz3v++Ab3mjdgtAumtqSZVcklNPduah2wiXyg4jz65FLemgRSlWTGDFsc5EcIBwk4OUZFdguikiAJGVtiY5VTfv/0kW5P1w="

language: php

cache:
  directories:
    - vendor

php:
  - 5.5
  - 5.6
  - 7

services:
  - memcached
  - redis
  - mysql

notifications:
  email:
    on_success: change
    on_failure: change

install:
  - composer config --global github-oauth.github.com $GITHUB_API_TOKEN
  - composer selfupdate
  - composer install -o -n --prefer-source
  - php -i

before_script:
  - mysql -e 'CREATE DATABASE ciims_travis;'
  - php web/index.php installer index --dbHost=127.0.0.1 --dbName=ciims_travis --dbUsername=root --dbPassword="" --adminEmail="travis@ciims.io" --adminPassword=travis --adminUsername=travis --siteName="CiiMS - Travis CI" --force=0 --writeConfig=1 --debug=1

script: 
  - ./vendor/bin/codecept run
  - ./vendor/bin/codecept run -c ./vendor/charlesportwoodii/cii
  - ./vendor/bin/codecept run -c ./protected/modules/api
  - ./vendor/bin/codecept run -c ./protected/modules/install
  - ./vendor/bin/codecept run -c ./protected/modules/dashboard
