language: php

php:
  - 5.3 # Codeception 2.0 hardfails on PHP 5.3 due to dependency issues. No longer testing on
  - 5.4
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.3

services:
  - memcached
  - redis
  - mysql

notifications:
  email:
    on_success: change
    on_failure: change
    
before_script:
  - composer selfupdate
  - composer install # Install rather than update
  - php -i
  - mysql -e 'create database ciims_travis;'
  - echo "2.0.0-dev" > protected/config/VERSION
  - php protected/yiic.php installer index --dbHost=127.0.0.1 --dbName=ciims_travis --dbUsername=root --dbPassword="" --adminEmail="travis@ciims.io" --adminPassword=travis --adminUsername=travis --siteName="CiiMS - Travis CI"


script: ./vendor/bin/codecept run
