language: php

php:
  - 5.3 #codeception will fail on 5.3
  - 5.4
  - 5.5
#  - hhvm

services:
  - memcached
  - redis
  - mysql

notifications:
  email:
    on_success: change
    on_failure: never
    
before_script:
  - rm composer.lock
  - composer selfupdate
  - composer install					
  - mysql -e 'create database ciims_test;'
  - echo "https://$TRAVIS_BUILD_NUMBER-$TRAVIS_BUILD_ID-$TRAVIS_JOB_ID.travis-ci.org" > protected/runtime/hostname
  - php protected/tyiic.php migrate up --interactive=0
  - ./vendor/bin/codecept build || true

script: ./vendor/bin/codecept run
