language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
#  - hhvm

services:
  - memcached
  - redis
  - mysql

notifications:
  email:
    on_success: change
    on_failure: never
    
before_script:
  - php composer.phar install
  - mysql -e 'create database ciims_test;'          # Create Database
  - php yiic-test.php migrate up --interactive=0    # Run Migrations
  - cd tests                                        # Navigate to the Tests Directory to run the tests